// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Runtime.Serialization;

namespace ImageDescrypt.Entity
{
    public class HISTORYGAMESERVER
    {
        [DataMember]
        public string GAME_NAME { get; set; }
        [DataMember]
        public string GAME_KEY { get; set; }
        [DataMember]
        public int GAME_ID { get; set; }
        [DataMember]
        public string SID { get; set; }
        [DataMember]
        public string SERVER_NAME { get; set; }
        [DataMember]
        public string SERVER_URL { get; set; }
        [DataMember]
        public int HOTSORT { get; set; }
    }

    public class HISTORY
    {
        [DataMember]
        public string str237 { get; set; }
    }

    public class HISTORYHOTGAMESERVER
    {
        [DataMember]
        public string GAME_NAME { get; set; }
        [DataMember]
        public string GAME_KEY { get; set; }
        [DataMember]
        public string GAME_ID { get; set; }
        [DataMember]
        public string SID { get; set; }
        [DataMember]
        public string SERVER_NAME { get; set; }
        [DataMember]
        public string SERVER_URL { get; set; }
        [DataMember]
        public int HOTSORT { get; set; }
        [DataMember]
        public string STATE { get; set; }
    }

    public class Userinfo
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string LOGIN_ACCOUNT { get; set; }
        [DataMember]
        public int IS_ADULT { get; set; }
        [DataMember]
        public string LAST_LOGIN_IP { get; set; }
        [DataMember]
        public string LAST_LOGIN_TIME { get; set; }
        [DataMember]
        public IList<HISTORYGAMESERVER> HISTORY_GAME_SERVER { get; set; }
        [DataMember]
        public object VIP { get; set; }
        [DataMember]
        public int PHONE_BIND { get; set; }
        [DataMember]
        public int COIN { get; set; }
        [DataMember]
        public int POINT { get; set; }
        [DataMember]
        public int VIP_DEEP { get; set; }
        [DataMember]
        public int VIP_EXP { get; set; }
        [DataMember]
        public int VIP_UPPER { get; set; }
        [DataMember]
        public string HEADER { get; set; }
        [DataMember]
        public HISTORY HISTORY { get; set; }
        [DataMember]
        public object VIPTOGAME { get; set; }
        [DataMember]
        public string NICK { get; set; }
        [DataMember]
        public int SET_NICK_NUM { get; set; }
        [DataMember]
        public string FORBID_DATE { get; set; }
        [DataMember]
        public int FORBID_TIMES { get; set; }
        [DataMember]
        public string ALIAS_ACCOUNT { get; set; }
        [DataMember]
        public string AUTH_TYPE { get; set; }
        [DataMember]
        public string AUTH_NICKNAME { get; set; }
        [DataMember]
        public string AVATAR_URL { get; set; }
        [DataMember]
        public string AVATAR_REMOVE_TIME { get; set; }
        [DataMember]
        public string SHOW_NAME { get; set; }
        [DataMember]
        public string SHOW_HEADER { get; set; }
        [DataMember]
        public int IS_ALIAS_HEADER { get; set; }
        [DataMember]
        public IList<HISTORYHOTGAMESERVER> HISTORY_HOT_GAMESERVER { get; set; }
    }

    public class webLoginRetInfo
    {
        [DataMember]
        public string success { get; set; }
        [DataMember]
        public string url { get; set; }
        [DataMember]
        public string message { get; set; }
        [DataMember]
        public int is_hg { get; set; }
        [DataMember]
        public string game_id { get; set; }
        [DataMember]
        public int game_server_id { get; set; }
        [DataMember]
        public Userinfo userinfo { get; set; }
    }

}
