// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Runtime.Serialization;

namespace ImageDescrypt.Entity
{

    public class webLoginRetInfo2
    {
        [DataMember]
        public int gonggaoRollOn { get; set; }
        [DataMember]
        public string gameId { get; set; }
        [DataMember]
        public string gameName { get; set; }
        [DataMember]
        public string gameUrl { get; set; }
        [DataMember]
        public string gameKey { get; set; }
        [DataMember]
        public string currentServerName { get; set; }
        [DataMember]
        public string username { get; set; }
        [DataMember]
        public string serverId { get; set; }
        [DataMember]
        public string sId { get; set; }
        [DataMember]
        public string exts { get; set; }
        [DataMember]
        public string nowTime { get; set; }
        [DataMember]
        public string logRefer { get; set; }
        [DataMember]
        public string logParam { get; set; }
        [DataMember]
        public bool isGeneralize { get; set; }
        [DataMember]
        public int skinType { get; set; }
        [DataMember]
        public int specialGame { get; set; }
        [DataMember]
        public int isSwUser { get; set; }
    }

}
