// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Runtime.Serialization;

namespace CCPRestSDK
{

    public class Account
    {
        [DataMember]
        public string status { get; set; }
        [DataMember]
        public string type { get; set; }
        [DataMember]
        public string dateUpdated { get; set; }
        [DataMember]
        public string balance { get; set; }
        [DataMember]
        public string subBalance { get; set; }
        [DataMember]
        public string dateCreated { get; set; }
    }

    public class TemplateSMS
    {
        [DataMember]
        public string smsMessageSid { get; set; }
        [DataMember]
        public string dateCreated { get; set; }
    }

    public class webQueryInfo
    {
        [DataMember]
        public string statusMsg { get; set; }
        [DataMember]
        public string statusCode { get; set; }
        [DataMember]
        public Account Account { get; set; }
        [DataMember]
        public TemplateSMS templateSMS { get; set; }
    }

}
