// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Runtime.Serialization;

namespace ImageDescrypt.Entity
{

    public class webServerInfo
    {
        [DataMember]
        public string pf { get; set; }
        [DataMember]
        public string ip { get; set; }
        [DataMember]
        public string port { get; set; }
        [DataMember]
        public string sport { get; set; }
        [DataMember]
        public string serverId { get; set; }
        [DataMember]
        public string user_name { get; set; }
        [DataMember]
        public string user_info { get; set; }
        [DataMember]
        public string is_adult { get; set; }
        [DataMember]
        public string time { get; set; }
        [DataMember]
        public string logintype { get; set; }
        [DataMember]
        public string autoLogin { get; set; }
        [DataMember]
        public string real_user { get; set; }
        [DataMember]
        public string rest_params { get; set; }
        [DataMember]
        public string resHost { get; set; }
        [DataMember]
        public string sign { get; set; }
        [DataMember]
        public string platformVars { get; set; }
    }

}
