// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.Serialization;

namespace ImageDescrypt
{

  [DataContract]
    internal class TimeInfo
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class XscbInfo
    {

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int IsBuy { get; set; }

        [DataMember]
        public int Inspire { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int IsCompose { get; set; }

        [DataMember]
        public int IsCleanCd { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public TimeInfo TimeInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class AutoSortBackpackInfo
    {

        [DataMember]
        public int AutoYongbingExpItem { get; set; }

        [DataMember]
        public IList<int> AutoList { get; set; }

        [DataMember]
        public IList<int> AutoSellList { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public IList<int> AutoItems { get; set; }

        [DataMember]
        public int AutoStore { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int AutoSell { get; set; }

        [DataMember]
        public IList<object> AutoSellItems { get; set; }

        [DataMember]
        public int AutoExpItem { get; set; }

        [DataMember]
        public int AutoResolve { get; set; }

        [DataMember]
        public int AutoGuild { get; set; }

        [DataMember]
        public IList<object> AutoItemIds { get; set; }

        [DataMember]
        public IList<object> AutoSellItemIds { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo
    {

        [DataMember]
        public int ExpItem1 { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int ExpItem2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int ExpItem3 { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }
    }

  [DataContract]
    internal class TimeInfo2
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class AnglebossInfo
    {

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int AutoAddTime { get; set; }

        [DataMember]
        public int MonIndex { get; set; }

        [DataMember]
        public int AutoBuyTicket { get; set; }

        [DataMember]
        public UseItemInfo UseItemInfo { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public TimeInfo2 TimeInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class DailyTaskInfo
    {

        [DataMember]
        public int AutoHigh { get; set; }

        [DataMember]
        public int AutoLow { get; set; }

        [DataMember]
        public int IsOnekey { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int IsTransfer { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class TimeInfo3
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class WarpgateInfo
    {

        [DataMember]
        public int AutoAdd { get; set; }

        [DataMember]
        public int HardIndex { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int AutoAddNum { get; set; }

        [DataMember]
        public int AutoResolve { get; set; }

        [DataMember]
        public int AutoResolveIndex { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int MapIndex { get; set; }

        [DataMember]
        public TimeInfo3 TimeInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo2
    {

        [DataMember]
        public int SpeedTask2 { get; set; }

        [DataMember]
        public int SpeedTask3 { get; set; }

        [DataMember]
        public int SpeedLhgc { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int ExpTask1 { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int ExpTask2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpTaskLhgc { get; set; }

        [DataMember]
        public int SpeedTask1 { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class PublicFightInfo
    {

        [DataMember]
        public int AutoAward { get; set; }

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public bool Save2 { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public IList<object> SkillIdList { get; set; }

        [DataMember]
        public int Time2 { get; set; }

        [DataMember]
        public IList<object> SkillIdList1 { get; set; }

        [DataMember]
        public int Time1 { get; set; }

        [DataMember]
        public IList<object> SkillIdList2 { get; set; }

        [DataMember]
        public IList<object> SkillIdList0 { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int UseSkillIndex { get; set; }

        [DataMember]
        public bool Save0 { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public bool Save1 { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo3
    {

        [DataMember]
        public int ExpItem1 { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int ExpItem2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int ExpItem3 { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }
    }

  [DataContract]
    internal class TimeInfo4
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class QjIslandInfo
    {

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int AutoAddTime { get; set; }

        [DataMember]
        public int MonIndex { get; set; }

        [DataMember]
        public int AutoBuyTicket { get; set; }

        [DataMember]
        public UseItemInfo3 UseItemInfo { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public TimeInfo4 TimeInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class HYSYInfo
    {

        [DataMember]
        public int AutoAward { get; set; }

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public bool Save2 { get; set; }

        [DataMember]
        public IList<object> SkillIdList { get; set; }

        [DataMember]
        public int Time2 { get; set; }

        [DataMember]
        public IList<object> SkillIdList1 { get; set; }

        [DataMember]
        public int Time1 { get; set; }

        [DataMember]
        public IList<object> SkillIdList2 { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int Time3 { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int UseSkillIndex { get; set; }

        [DataMember]
        public bool Save0 { get; set; }

        [DataMember]
        public IList<object> SkillIdList0 { get; set; }

        [DataMember]
        public bool Save1 { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class TimeInfo5
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class BossInfo
    {

        [DataMember]
        public int ReliveTimeNum { get; set; }

        [DataMember]
        public IList<object> BossList3 { get; set; }

        [DataMember]
        public int CurBossId { get; set; }

        [DataMember]
        public int CurBossMapId { get; set; }

        [DataMember]
        public int HasBeginAttack { get; set; }

        [DataMember]
        public int TotalReliveCount { get; set; }

        [DataMember]
        public int LowToHight { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int Prepare { get; set; }

        [DataMember]
        public int PrepareTime { get; set; }

        [DataMember]
        public int KeepWait { get; set; }

        [DataMember]
        public TimeInfo5 TimeInfo { get; set; }

        [DataMember]
        public IList<object> BossList1 { get; set; }

        [DataMember]
        public int ReliveTime { get; set; }

        [DataMember]
        public IList<object> BossList2 { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class SignInfo
    {

        [DataMember]
        public int NeedCheckSign { get; set; }

        [DataMember]
        public int GetActiveAward { get; set; }

        [DataMember]
        public int ReturnExpLevel { get; set; }

        [DataMember]
        public int GetReturnExpAward { get; set; }

        [DataMember]
        public int FillupSign { get; set; }

        [DataMember]
        public int AutoSign { get; set; }

        [DataMember]
        public int GuildAward { get; set; }

        [DataMember]
        public int GetSignAward { get; set; }

        [DataMember]
        public int JingpoMoney { get; set; }

        [DataMember]
        public int NeedSign { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int JingpoGold { get; set; }

        [DataMember]
        public int NeedFillupSign { get; set; }

        [DataMember]
        public int JingpoGoldTimes { get; set; }

        [DataMember]
        public int NeedGuildAward { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo4
    {

        [DataMember]
        public int ExpItem1 { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int ExpItem2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int ExpItem3 { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }
    }

  [DataContract]
    internal class TimeInfo6
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class LhgcInfo
    {

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int IsBuy { get; set; }

        [DataMember]
        public int Inspire { get; set; }

        [DataMember]
        public UseItemInfo4 UseItemInfo { get; set; }

        [DataMember]
        public int UseSlowDown { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public TimeInfo6 TimeInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo5
    {

        [DataMember]
        public int ExpItem1 { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int ExpItem2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int ExpItem3 { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }
    }

  [DataContract]
    internal class WolfInfo
    {

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int Inspire { get; set; }

        [DataMember]
        public UseItemInfo5 UseItemInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo6
    {

        [DataMember]
        public int ExpItem1 { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int ExpItem2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int ExpItem3 { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }
    }

  [DataContract]
    internal class TimeInfo7
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class EmgcInfo
    {

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int IsBuy { get; set; }

        [DataMember]
        public int Inspire { get; set; }

        [DataMember]
        public UseItemInfo6 UseItemInfo { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int IsCompose { get; set; }

        [DataMember]
        public int IsCleanCd { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public TimeInfo7 TimeInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class MainTaskInfo
    {

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int IsTransfer { get; set; }

        [DataMember]
        public int IsReceive { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class AutoInfo
    {

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int IsPlayer { get; set; }

        [DataMember]
        public int Posx { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int Posy { get; set; }

        [DataMember]
        public int MapId { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo7
    {

        [DataMember]
        public int ExpItem1 { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int ExpItem2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int ExpItem3 { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }
    }

  [DataContract]
    internal class TimeInfo8
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class StoneCopyInfo
    {

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int IsBuy { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int Inspire { get; set; }

        [DataMember]
        public UseItemInfo7 UseItemInfo { get; set; }

        [DataMember]
        public int UseSlowDown { get; set; }

        [DataMember]
        public int CheckAutobtn { get; set; }

        [DataMember]
        public int CheckAutobtn1 { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int CheckAutobtn2 { get; set; }

        [DataMember]
        public int CheckAutobtn3 { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int CheckAutobtn4 { get; set; }

        [DataMember]
        public TimeInfo8 TimeInfo { get; set; }

        [DataMember]
        public int CheckAutoRelive { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class UseItemInfo8
    {

        [DataMember]
        public int ExpItem1 { get; set; }

        [DataMember]
        public int AutoBuySpeed { get; set; }

        [DataMember]
        public int ExpItem2 { get; set; }

        [DataMember]
        public int ExpItemIndex { get; set; }

        [DataMember]
        public int ExpItem3 { get; set; }

        [DataMember]
        public int SpeedItem { get; set; }

        [DataMember]
        public int ExpItem { get; set; }

        [DataMember]
        public int AutoBuyExp { get; set; }
    }

  [DataContract]
    internal class TimeInfo9
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class IslandInfo
    {

        [DataMember]
        public int TotalCount { get; set; }

        [DataMember]
        public int IsAutoAddBuff { get; set; }

        [DataMember]
        public UseItemInfo8 UseItemInfo { get; set; }

        [DataMember]
        public int IsAutoUseGold { get; set; }

        [DataMember]
        public int AutoAddBuffTime { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public int AutoAddBuffCount { get; set; }

        [DataMember]
        public int IsCleanCd { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public TimeInfo9 TimeInfo { get; set; }

        [DataMember]
        public int Count { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

  [DataContract]
    internal class TimeInfo10
    {

        [DataMember]
        public int AutoTime { get; set; }

        [DataMember]
        public int Hour { get; set; }

        [DataMember]
        public int Min { get; set; }
    }

  [DataContract]
    internal class VipBossInfo
    {

        [DataMember]
        public int AutoBoss2 { get; set; }

        [DataMember]
        public int AutoBoss3 { get; set; }

        [DataMember]
        public int AutoBoss1 { get; set; }

        [DataMember]
        public int AllowExecute { get; set; }

        [DataMember]
        public int CurSate { get; set; }

        [DataMember]
        public TimeInfo10 TimeInfo { get; set; }

        [DataMember]
        public int AutoBoss4 { get; set; }

        [DataMember]
        public int IconNum { get; set; }
    }

}

namespace ImageDescrypt
{

  [DataContract]
    internal class SampleReverse
    {

        [DataMember]
        public XscbInfo XscbInfo { get; set; }

        [DataMember]
        public AutoSortBackpackInfo AutoSortBackpackInfo { get; set; }

        [DataMember]
        public AnglebossInfo AnglebossInfo { get; set; }

        [DataMember]
        public DailyTaskInfo DailyTaskInfo { get; set; }

        [DataMember]
        public WarpgateInfo WarpgateInfo { get; set; }

        [DataMember]
        public UseItemInfo2 UseItemInfo { get; set; }

        [DataMember]
        public PublicFightInfo PublicFightInfo { get; set; }

        [DataMember]
        public QjIslandInfo QjIslandInfo { get; set; }

        [DataMember]
        public HYSYInfo HYSYInfo { get; set; }

        [DataMember]
        public BossInfo BossInfo { get; set; }

        [DataMember]
        public SignInfo SignInfo { get; set; }

        [DataMember]
        public LhgcInfo LhgcInfo { get; set; }

        [DataMember]
        public WolfInfo WolfInfo { get; set; }

        [DataMember]
        public EmgcInfo EmgcInfo { get; set; }

        [DataMember]
        public MainTaskInfo MainTaskInfo { get; set; }

        [DataMember]
        public AutoInfo AutoInfo { get; set; }

        [DataMember]
        public StoneCopyInfo StoneCopyInfo { get; set; }

        [DataMember]
        public IslandInfo IslandInfo { get; set; }

        [DataMember]
        public VipBossInfo VipBossInfo { get; set; }
    }

}
